### PR TITLE
Add StringStack and DoubleStack.

### PR DESCRIPTION
**Pull request by vilichtSarina**
sorry, sadly lots of metadata pushed, will adjust gitignore after (forgot to check what i'm adding to the commit).

### CODE REVIEW

**Comment by vilichtSarina** [comment]
@AW0000 Hi, Could you please review this change?

**Review by AW0000 — APPROVED** [review]
LGTM, code looks good to me :)

**Review by AW0000 — COMMENTED** [review]
LGTM ;)

**Review by AW0000 — COMMENTED** [review]
LGTM

**Pull request merged**
